name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          echo "🕒 Запуск пинга в $(date)"
          curl -f -s -o /dev/null -w "Status: %{http_code}\n" https://elite-doors.shop/api/keep-alive
          echo "✅ Пинг выполнен в $(date)"